 # 📘 Veri Bilimi Ödevi – Numpy ve Pandas Uygulamaları 

## 1. Numpy Bölümü 

### 1.1. Numpy ile Matris İşlemleri 

In [2]:
import numpy as np
matris = np.random.randint(0, 101, (5, 5))
print("Matris:\n", matris)

ortalama = np.mean(matris)
std = np.std(matris)
varyans = np.var(matris)

maks = np.max(matris)
minimum = np.min(matris)

kosegen_toplam = np.trace(matris)

print("\nOrtalama:", ortalama)
print("Standart Sapma:", std)
print("Varyans:", varyans)
print("En büyük değer:", maks)
print("En küçük değer:", minimum)
print("Köşegen toplamı:", kosegen_toplam)

Matris:
 [[97 11 31 38 80]
 [11 69 54 97 95]
 [78 87 73 24 46]
 [77 31 76 79 35]
 [36 45 34 28 11]]

Ortalama: 53.72
Standart Sapma: 28.00645639848069
Varyans: 784.3616000000001
En büyük değer: 97
En küçük değer: 11
Köşegen toplamı: 329


### 1.2. Numpy ile Veri Simülasyonu 

In [5]:
puanlar = np.random.normal(loc=70, scale=15, size=1000)
puanlar = np.clip(puanlar, 0, 100)

ortalama_puan = np.mean(puanlar)
medyan_puan = np.median(puanlar)
std_puan = np.std(puanlar)

dusuk_alan = np.sum(puanlar < 50)

print("Ortalama:", ortalama_puan)
print("Medyan:", medyan_puan)
print("Standart Sapma:", std_puan)
print("50'den düşük alan öğrenci sayısı:", dusuk_alan)

Ortalama: 69.7503647638262
Medyan: 70.00892777339675
Standart Sapma: 14.657810396974021
50'den düşük alan öğrenci sayısı: 95


## 2. Pandas Bölümü 

In [6]:
import pandas as pd

data = {
    "Öğrenci": ["Ali", "Ayşe", "Mehmet", "Zeynep", "Ahmet"],
    "Yaş": [20, 21, 19, 22, 20],
    "Bölüm": ["Bilgisayar", "Fizik", "Kimya", "Bilgisayar", "Fizik"],
    "Matematik": [70, 60, 80, 90, 55],
    "Fizik": [65, 75, 70, 85, 60],
    "Kimya": [80, 85, 65, 95, 70]
}

df = pd.DataFrame(data)
print(df)

ders_ort = df[["Matematik", "Fizik", "Kimya"]].mean()
print("Her dersin ortalaması:\n", ders_ort)

en_yuksek_mat_index = df["Matematik"].idxmax()
en_yuksek_mat_ogrenci = df.loc[en_yuksek_mat_index, "Öğrenci"]
print("En yüksek matematik notunu alan öğrenci:", en_yuksek_mat_ogrenci)

df["Ortalama"] = df[["Matematik", "Fizik", "Kimya"]].mean(axis=1)
print(df)

bolum_ort = df.groupby("Bölüm")[["Matematik", "Fizik", "Kimya", "Ortalama"]].mean()
print("Bölümlere göre ortalamalar:\n", bolum_ort)

basarili_ogrenciler = df[df["Ortalama"] > 70]
print("Ortalaması 70'in üzerinde olan öğrenciler:\n", basarili_ogrenciler)

  Öğrenci  Yaş       Bölüm  Matematik  Fizik  Kimya
0     Ali   20  Bilgisayar         70     65     80
1    Ayşe   21       Fizik         60     75     85
2  Mehmet   19       Kimya         80     70     65
3  Zeynep   22  Bilgisayar         90     85     95
4   Ahmet   20       Fizik         55     60     70
Her dersin ortalaması:
 Matematik    71.0
Fizik        71.0
Kimya        79.0
dtype: float64
En yüksek matematik notunu alan öğrenci: Zeynep
  Öğrenci  Yaş       Bölüm  Matematik  Fizik  Kimya   Ortalama
0     Ali   20  Bilgisayar         70     65     80  71.666667
1    Ayşe   21       Fizik         60     75     85  73.333333
2  Mehmet   19       Kimya         80     70     65  71.666667
3  Zeynep   22  Bilgisayar         90     85     95  90.000000
4   Ahmet   20       Fizik         55     60     70  61.666667
Bölümlere göre ortalamalar:
             Matematik  Fizik  Kimya   Ortalama
Bölüm                                         
Bilgisayar       80.0   75.0   87.5  80.833333